// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWv6e8-1iTN8wTS97u2Qba1AgD4BLnxI',
    appId: '1:243454829849:web:b24067c6045cc42e1dd188',
    messagingSenderId: '243454829849',
    projectId: 'supervisorportal-f0530',
    authDomain: 'supervisorportal-f0530.firebaseapp.com',
    storageBucket: 'supervisorportal-f0530.appspot.com',
    measurementId: 'G-8QHJ83Y8GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2uuH1iXBqiEZt0su6HYYj5In7byRnbZ4',
    appId: '1:243454829849:android:58406245fa499f551dd188',
    messagingSenderId: '243454829849',
    projectId: 'supervisorportal-f0530',
    storageBucket: 'supervisorportal-f0530.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKs3qKxrn9Nz62BE6Z5kgOa4dnG7qyxJI',
    appId: '1:243454829849:ios:bd27b51279ee366a1dd188',
    messagingSenderId: '243454829849',
    projectId: 'supervisorportal-f0530',
    storageBucket: 'supervisorportal-f0530.appspot.com',
    iosClientId: '243454829849-rabs8mk7bismvkokrsovqdp0jdn77he5.apps.googleusercontent.com',
    iosBundleId: 'com.example.intp22Vis3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKs3qKxrn9Nz62BE6Z5kgOa4dnG7qyxJI',
    appId: '1:243454829849:ios:bd27b51279ee366a1dd188',
    messagingSenderId: '243454829849',
    projectId: 'supervisorportal-f0530',
    storageBucket: 'supervisorportal-f0530.appspot.com',
    iosClientId: '243454829849-rabs8mk7bismvkokrsovqdp0jdn77he5.apps.googleusercontent.com',
    iosBundleId: 'com.example.intp22Vis3',
  );
}
